### ISSUE TITLE
Not sure which branch to use

### ISSUE THREAD

**Issue by Lightosk** [healingbrew/UAssetParser#10]
Since I'm using this for another project, I was thinking about which branch should I use - the `core` branch is newer, but seems to have some significant changes, the `master` branch is... well, the branch you see first. The `master` branch is set as the default branch, too.

**Comment by Kein** [comment]
`Core` rewrite is not on par yet, use the framework version (`master`)

**Comment by Lightosk** [comment]
Ok, do you know when it will be ready? If I datamine one large database, I have an failure rate of 33%. So I'd be very happy about a fix.

**Comment by Lightosk** [comment]
Ok, do you know when it will be ready? If I datamine one large database, I have an failure rate of 33%. So I'd be very happy about a fix.

**Comment by healingbrew** [comment]
No ETA. Master and Core will be developed concurrently.

**Comment by Lightosk** [comment]
Made a new issue, because it has nothing to do with "Not sure which branch to use" any more.
#13
