### ISSUE TITLE
[Feature Request] Command line option to check if file is parsable

### ISSUE THREAD

**Issue by Lightosk** [healingbrew/UAssetParser#18]
Hello, me again, I wrote myself an (Python) script, which gives me a nice GUI to interact with. It has one problem: It runs through **each** .uasset file in the directory I gave it. Even if this is a texture, the script tries to run an executable of your repository, and... fails. The most of it's time it's just saying, that it got an error in the executable. So here I request an command-line option to check if the file is an datatable/stringtable. Then it could just print out true/false, 0/1 or it's exit code. This option would really be only a "quick check", no approach to parse to waste time, as it does now.

**Comment by Kein** [comment]
> check if the file is an datatable/stringtable.

In order to check this you need to parse the file anyway and it already does that and throws exception if it can't or structure is invalid.

May be you want a switch for "silent failure" that swallows the exception and continue? This can be done.

**Comment by healingbrew** [comment]
Should be possible, but it'll be added to the `core` branch since that's using a more robust CLI parsing thing.

**Comment by Lightosk** [comment]
I really thank you for your help. I'm looking forward to get this issue closed.

**Comment by healingbrew** [comment]
If you pass  -n to the argument list, it will only check if it can serialize. If it can't, it returns 2.
Other error codes are -1 (0xFFFFFFFF) for unexpected flag error, and 1 for unexpected program error.

**Comment by healingbrew** [comment]
Builds can be found here now: https://ci.appveyor.com/project/yretenai/uassetparser/build/artifacts

UObjectDebug is a debug build, with full debugging symbols.
UObjectRuntime is JUST the compiled project without any C# runtime/support files
UObjectStandalone is the project along with C# runtime and support files.
