### ISSUE TITLE
I got a System.OverflowException error

### ISSUE THREAD

**Issue by TgamesFR** [healingbrew/UAssetParser#5]
Hi healingbrew,

I got an System.OverflowException : 'Array dimensions exceeded supported range.'
With using your UAssetParser with theses files :

[UassetExampleFile.zip](https://github.com/healingbrew/UAssetParser/files/3531036/UassetExampleFile.zip)

When trying to change how it's calculated the size i got after a read of the FName = [FObjectExport [FName "/Game/Art/LightFunctions/M_FlashlightFunction_01" (0)]]
but another error with a null value somewhere.

Can you look into it ?

Thanks.

**Comment by TgamesFR** [comment]
Here is also more example of Uasset and Uexp files who doesn't works on UAssetParser.
[MoreUassetExamplesFiles.zip](https://github.com/healingbrew/UAssetParser/files/3531051/MoreUassetExamplesFiles.zip)

**Comment by Kein** [comment]
UAssetParser only properly supports DataTables and StringTables. Additionally, you have multiple exports in your example, they arent correctly processed still.

**Comment by TgamesFR** [comment]
Thanks for your fast answer. I just want to list all offsets of each float data. To found the value in the exp file. Someone has made a private tool to list all data of Uasset files to JSON. But the software is private, i just got some export he made.
[ExportInJSON.zip](https://github.com/healingbrew/UAssetParser/files/3531334/ExportInJSON.zip)

It's possible to just list me "name_offset": of each data from XXXXXXXX.uasset.ObjectSummary.json ?
I just need this data in my work.

**Comment by Kein** [comment]
No, because what you ask for is Export Data which cannot be parsed by UAsset since your example is not a DataTable or StringTable. UAsset is capable parsing only header meta, which is useless to you.

**Comment by TgamesFR** [comment]
Ok i understand. Do you have any clue or informations who can helps me to found each offsets pointers referenced to each data listed in the uasset ? Because it's really hard to found values in the uexp without know the offset in HxD :(. For the moment i tried with no luck...

**Comment by Kein** [comment]
Sure:
https://github.com/EpicGames/UnrealEngine
namely see `CoreUObject`
You need to join the group. Have fun.

**Comment by TgamesFR** [comment]
How to join us ?

**Comment by TgamesFR** [comment]
Thanks i'm on it ;)

**Comment by TgamesFR** [comment]
UnrealEngine\UnrealEngine-4.18.2-release\Engine\Source\Runtime\CoreUObject
It's the correct path where i need to look ?
I'm using 4.18.2 it's with this version uasset has been made.

**Comment by healingbrew** [comment]
Stale issue closed.
