### ISSUE TITLE
BoolProperty bug

### ISSUE THREAD

**Issue by Ekey** [healingbrew/UAssetParser#7]
When testing this tool, I sometimes get the following exception:

`Unhandled exception. System.NotImplementedException: No parser for BoolProperty`

This property is implemented, but I found an small bug in the code: VisitorFactory.cs => Line 44: is written by "BoolPro**pr**ety" instead of "BoolProperty". 2 letters are confused :)
After fixing it works fine ;)

You can also add some new properties such as these:

```
{ "Int16Property", (r,s,c) => r.ReadInt16() },
{ "UInt16Property", (r,s,c) => r.ReadUInt16() },
{ "Int64Property", (r,s,c) => r.ReadInt64() },
{ "UInt64Property", (r,s,c) => r.ReadUInt64() },
```

On those files that I tested they are present :)

Best regards!

**Comment by Kein** [comment]
Which game has Uint16 and Uint64?

**Comment by Ekey** [comment]
Files from [Traha.](https://traha.nexon.com) [Here](https://www117.zippyshare.com/v/yRANvJZa/file.html) these files if you are interested.

**Comment by healingbrew** [comment]
Fixed the typo, and added different variations. Should be an innocent enough change.
